### ISSUE TITLE
Cellebrite Tar

### ISSUE THREAD

**Issue by jerseyjuntollc** [ydkhatri/mac_apt#48]
Will this work with a Cellebrite tar?  We opened the tar and there wasn't the iOS structure spoken about in the documentation.

**Comment by ydkhatri** [comment]
Yes. 
You will have to extract the tar (or dar) file's content onto a folder on the disk, then use that folder as input_path. Since ios folder structures can result in very long paths for some files/folders, it is recommended to extract very close to root as possible (to reduce path length as much as possible). I usually use `C:\fs` or something like that.

**Comment by jerseyjuntollc** [comment]
The think is, when we extracted the tar there were no folders just a large amount of files.

**Comment by ydkhatri** [comment]
ios_apt only works with a full file system extraction. It won't work with itunes/finder backups (or other forms of extraction). If you can post a screenshot, I can try to tell what you might have. Email me if you don't want it here publicly.

**Comment by ydkhatri** [comment]
Closing for lack of response
