### ISSUE TITLE
Last Tabs, Current Tabs, Last Session, and Current Session are no longer used

### ISSUE THREAD

**Issue by mnrkbys** [ydkhatri/mac_apt#92]
I have not gone over the details yet, but the above file does not currently exist.
Instead, it appears that Session_* and Tabs_* in the Sessions folder will need to be parsed.

You can check the file structure of Chrome following URL.
https://dfir.blog/chrome-evolution/

The above files exist until version 85, but not since version 86.
The latest version (version 112) adopts SNSS v3.

**Comment by ydkhatri** [comment]
You are correct. The format is not too complicated, I'll try to incorporate it this week.

**Comment by ydkhatri** [comment]
Now fixed in [dbeb1b5](https://github.com/ydkhatri/mac_apt/commit/dbeb1b5602ff5de7ef62d12b3f0f02294a81df38). It was a small tweak to support v3. Also changed CHROME to CHROMIUM to support Microsoft Edge (yes, I've seen it on people's mac systems!). 

Need to add paths to other Chromium browser folders (Vivaldi, Opera, Brave, ..) to support them all under the same plugin.

**Comment by mnrkbys** [comment]
I have posted the PR of #93.

**Comment by ydkhatri** [comment]
Thanks, will merge this one now.
